### ISSUE TITLE
Can't load image in css

### ISSUE THREAD

**Issue by alwaysonlinetxm** [rollup/rollup#1502]
I find out that rollup will not load the image url written in css/scss files. Just live below:
```CSS
.tit {
  ...
  background: url(./images/tit.png) no-repeat;
}
```

Rollup will just copy the url to the bundle file and do nothing else. So it makes me can't use background in css but only <img>.
I tried to write a plugin to solve this problem, but I find that rollup even will not treat the url as a file but just a string! So I don't know what I can do. Is this a bug of rollup?
