### ISSUE TITLE
output.assetFileNames, separate subdirectories by file type, the background image url of the css file is incorrect

### ISSUE THREAD

**Issue by guoxinman** [rollup/rollup#4899]
### Rollup Version

v3.15.0

### Operating System (or Browser)

windows 10

### Node Version (if applicable)

v16.16.0

### Link To Reproduction

no

### Expected Behaviour

```js
assetFileNames(assetInfo) {
	const assetsFileNamesMap = new Map([
		[/.(png|jpg|jpeg|gif|svg|webp)$/, '/img/[name]'],
		[/.css$/, '/css/[name]-[hash]']
	])

	for (const [reg, value] of assetsFileNamesMap.entries()) {
		if (reg.test(assetInfo.name)) return `assets${value}[extname]`
	}

	return 'assets/[name]-[hash][extname]'
}
```
expected:
```css
.style {
  background-image: url(../img/img.png)
}

### Actual Behaviour

```css
.style {
  background-image: url(./img/img.png)
}
```
but the background image url of the css file is incorrect
